### ISSUE TITLE
Need license

### ISSUE THREAD

**Issue by ches** [hspec/hspec.vim#2]
So that people can use and contribute with confidence. Using the Vim license (`:help license`) is somewhat common for plugins, but naturally I leave the choice to the original author.

**Comment by sol** [comment]
Any works for me. I use the MIT license for most of my projects, mostly because I prefer spending my time coding rather than reading lengthy software licenses.  But if the vim license has any practically benefits, is just the obvious choice or your preference for any other reason, then that's fine with me too.

Please feel free to add a license that you deem fit.

**Comment by ches** [comment]
I think the primary benefit of the Vim license is that it draws attention to a charity, but MIT is more liberal and you indeed have a point about it being immediately familiar to most potential contributors. There's not really a standard in the plugin community and MIT is common, so I'll stick with that.
